<html>
<head>
  <style>
    <!-- put your css here -->
  </style>
</head>
<body>
<div class="container">
  <div class="a4---2">
    <div class="wrapper-image-3-wrapper-text-ha-text-ngy wrap">
      <img class="image-6" src="res/images/image 3160-537.png" />
      <div class="wrapper-text-ha-text-ngy">
        <p class="text-ha-0">
          HÓA ĐƠN XUẤT KHO<br />KIÊM VẬN CHUYỂN NỘI BỘ
        </p>
        <p class="text-ngy-1">Ngày 08 tháng 07 năm 2023</p>
      </div>
      <div class="group-52">
        <p class="text-kh">Ký hiệu: 6K23NYY</p>
        <p class="text-kh">Số HĐ: 001324</p>
      </div>
    </div>
    <div class="wrapper-line-3-text-cng">
      <img class="line-26" src="res/images/Line 3160-536.png" />
      <p class="text-cng-0">CÔNG TY CỔ PHẦN NỘI THẤT HÒA PHÁT</p>
      <p class="text-normal">Mã số thuế: 0311942282</p>
      <p class="text-normal">
        Địa chỉ: Số 76 Đường số 2, Khu phố 5, Phường Bình Hưng Hòa B, Quận
        Bình Tân, Thành phố Hồ Chí Minh, Việt Nam
      </p>
      <p class="text-normal">Điện thoại: 0938024027</p>
      <img class="line-27" src="res/images/Line 2160-417.png" />
      <div class="wrapper-text-cn-text-ngy wrap">
        <p class="text-cn-0">
          Căn cứ lệnh điều động
          số:............................................
        </p>
        <p class="text-ngy-2">Ngày 08 tháng 07 năm 2023</p>
      </div>
      <p class="text-normal">
        của .........................................
        ....................................về việc:
        ...........................................................................
      </p>
      <p class="text-normal">
        Họ tên người vận chuyển:
        .............................................Hợp đồng số:
        ..................................................................
      </p>
      <p class="text-normal">
        Phương tiện vận chuyển:
        .....................................................................................................................................
      </p>
      <p class="text-normal">Xuất tại kho: CN Thủ Đức</p>
      <p class="text-normal">Nhập tại kho: CN Bình Thạnh</p>

      <div class="table-container">
        <table>
          <thead>
          <tr class="col-l-1 text-ngy-1">
            <th>STT</th>
            <th>Tên hàng hóa, dịch vụ</th>
            <th style="width: 10%">Mã số</th>
            <th style="width: 10%">Đơn vị tính</th>
            <th style="width: 5%">Thực xuất</th>
            <th style="width: 5%">Thực nhập</th>
            <th style="width: 10%">Đơn giá</th>
            <th style="width: 10%">Thành tiền</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td class="text-normal">1</td>
            <td class="text-normal">Bàn gỗ</td>
            <td class="text-normal"></td>
            <td class="text-normal">Cái</td>
            <td class="text-normal">5</td>
            <td class="text-normal"></td>
            <td class="text-normal"></td>
            <td class="text-normal"></td>
          </tr>
          <tr>
            <td class="text-normal">2</td>
            <td class="text-normal">Ghế gỗ</td>
            <td class="text-normal"></td>
            <td class="text-normal">Cái</td>
            <td class="text-normal">20</td>
            <td class="text-normal"></td>
            <td class="text-normal"></td>
            <td class="text-normal"></td>
          </tr>
          <tr>
            <td class="text-normal">3</td>
            <td class="text-normal">Bàn họp chân sắt</td>
            <td class="text-normal"></td>
            <td class="text-normal">Cái</td>
            <td class="text-normal">10</td>
            <td class="text-normal"></td>
            <td class="text-normal"></td>
            <td class="text-normal"></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td colspan="7" class="text-normal">Tổng cộng:</td>
            <td></td>
          </tr>
          <!-- Add more rows as needed -->
          </tbody>
        </table>
      </div>

      <div class="wrapper-text-ngi-text-th wrap">
        <p class="text-ngi-1">Người lập phiếu</p>
        <p class="text-th-1">Thủ kho xuất</p>
        <p class="text-ngi-2">Người vận chuyển</p>
        <p class="text-th-2">Thủ kho nhập</p>
      </div>
      <p class="text-k-5">(Ký và ghi rõ họ, tên)</p>
      <img class="image-7" src="res/images/image 2160-413.png" />
    </div>
  </div>
</div>
<!--<div class="container" style="padding-top: 100px;">-->
<!--  <div class="row justify-content-center">-->
<!--    <div class="col-md-6">-->
<!--      <table class="table table-bordered">-->
<!--        <thead class="thead-light">-->
<!--        <tr>-->
<!--          <th>Name</th>-->
<!--          <th>Address</th>-->
<!--        </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--        <tr>-->
<!--          <td>$name</td>-->
<!--          <td>$address</td>-->
<!--        </tr>-->
<!--        </tbody>-->
<!--      </table>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->
</body>
</html>